version: "3"
services:
  api:
    tty: true
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    depends_on:
      - db
    image: secret-recipes-api:latest
    container_name: family-recipes-api
    volumes:
      - ./api:/api
      - ./api/bundle:/bundle
    env_file:
      - config/.env
    environment:
      - RAILS_ENV=development
    ports:
      - 4000:4000

  db:
    build: ./db
    image: secret-recipes-db:latest
    container_name: family-recipes-db
    env_file:
      - config/.env
    volumes:
      - family-recipes-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    image: secret-recipes-client:latest
    container_name: family-recipes-client
    env_file:
      - config/.env
    volumes:
      - ./client:/usr/www
      - ./client/node_modules:/tmp/node_modules
      - .client/elm-stuff:/tmp/elm-stuff
    ports:
      - 8000:8000

volumes:
  family-recipes-db:
    driver: local
