version: "3"
services:
  api:
    build: ./api
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    depends_on:
      - db
    image: secret-recipes-api:latest
    container_name: family-recipes-api
    env_file:
      - config/.env
    environment:
      - RAILS_ENV=production
    ports:
      - 4000:4000

  db:
    build: ./db
    image: secret-recipes-db:latest
    container_name: family-recipes-db
    env_file:
      - config/.env
    volumes:
      - family-recipes-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  client:
    build: ./client
    command: nginx -c /usr/www/server/nginx.conf
    depends_on:
      - api
    image: secret-recipes-client:latest
    container_name: family-recipes-client
    env_file:
      - config/.env
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080

volumes:
  family-recipes-db:
    driver: local
