version: "3"
services:
  api:
    build: ./api
    depends_on:
      - db
    image: secret-recipes-api:latest
    container_name: family-recipes-api
    env_file:
      - config/.env
    ports:
      - 8088:8088

  db:
    build: ./db
    image: secret-recipes-db:latest
    container_name: family-recipes-db
    env_file:
      - config/.env
    volumes:
      - family-recipes-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  client:
    build: ./client
    image: secret-recipes-client:latest
    container_name: family-recipes-client
    env_file:
      - config/.env
    volumes:
      - ./client:/usr/www
      - ./client/node_modules:/tmp/node_modules
      - .client/elm-stuff:/tmp/elm-stuff
    ports:
      - 8000:8000

volumes:
  family-recipes-db:
    driver: local
